{
  "Psycho Cut": "念力切削",
  "Mud Shot": "噴泥",
  "Lick": "舔",
  "Scratch": "搔",
  "Water Gun": "噴水",
  "Metal Claw": "金屬爪",
  "Shadow Claw": "影子爪",
  "Wing Attack": "雙翼拍擊",
  "Vine Whip": "藤鞭",
  "Frost Breath": "冰之氣息",
  "Pound": "拍打",
  "Poison Jab": "毒刺",
  "Zen Headbutt": "思念頭槌",
  "Bug Bite": "蛀蝕",
  "Bite": "咬噬",
  "Dragon Breath": "龍之氣息",
  "Feint Attack": "佯攻",
  "Steel Wing": "鋼之翼",
  "Fire Fang": "火之牙",
  "Tackle": "撞擊",
  "Cut": "斬擊",
  "Poison Sting": "毒針",
  "Razor Leaf": "葉子飛刀",
  "Spark": "火花",
  "Sucker Punch": "突襲",
  "Acid": "溶解毒液",
  "Ember": "火苗",
  "Rock Throw": "落石",
  "Peck": "啄",
  "Bullet Punch": "彈子拳",
  "Low Kick": "下旋",
  "Thunder Shock": "電擊",
  "Confusion": "念力",
  "Quick Attack": "電光石火",
  "Fury Cutter": "連續斬擊",
  "Karate Chop": "手刀",
  "Ice Shard": "碎冰飛擊",
  "Bubble": "泡沫",
  "Mud Slap": "泥漿撥擊",
  "Rock Smash": "碎岩",
  "Splash": "鯉魚翻身",
  "Cross Chop": "十字斬",
  "Body Slam": "千斤鼎",
  "Dragon Claw": "龍爪",
  "Stone Edge": "石刃",
  "Brick Break ": "爆瓦片",
  "Aqua Tail": "液態尾巴",
  "Power Whip": "蠻力藤鞭",
  "Iron Head": "鐵頭槌",
  "Gunk Shot": "塵埃噴射",
  "Sludge Bomb": "污泥爆彈",
  "Leaf Blade": "葉刃斬",
  "Hurricane": "暴風",
  "Thunderbolt": "十萬伏特",
  "Psychic": "精神念力",
  "Sludge Wave": "污泥波浪",
  "Flamethrower": "火焰噴射",
  "Play Rough": "嬉鬧",
  "Megahorn": "超級角擊",
  "Thunder Punch": "雷拳",
  "Hyper Fang": "必殺門牙",
  "Discharge": "放電",
  "Cross Poison": "毒十字斬",
  "Heat Wave": "熱風",
  "Hydro Pump": "水柱巨砲",
  "Petal Blizzard": "落花飛雪",
  "Blizzard": "暴風雪",
  "Thunder": "轟天雷",
  "Psyshock": "念力衝擊",
  "Moonblast": "月亮攻擊",
  "Fire Blast": "大字燒",
  "Earthquake": "地震",
  "Submission": "地獄式滾動",
  "X-Scissor": "十字剪",
  "Flash Cannon": "光柵炮",
  "Drill Run": "鑽地",
  "Hyper Beam": "破壞光束",
  "Dragon Pulse": "龍之波動",
  "Power Gem": "力量寶石",
  "Psystrike": "念力暴擊",
  "Ice Beam": "冷凍光束",
  "Solar Beam": "陽光烈焰",
  "Shadow Ball": "影子球",
  "Dark Pulse": "闇之波動",
  "Ice Punch": "冷凍拳",
  "Seed Bomb": "種子爆彈",
  "Rock Slide": "崩石",
  "Bone Club": "骨頭棒",
  "Fire Punch": "火之拳",
  "Flame Burst": "爆裂火焰",
  "Stomp": "踐踏",
  "Bug Buzz": "蟲之鳴叫",
  "Signal Beam": "訊號光束",
  "Drill Peck": "鑽啄",
  "Low Sweep": "下段踢",
  "Night Slash": "試刀",
  "Rest": "睡眠",
  "Dazzling Gleam": "魔法照耀",
  "Giga Drain": "極級吸收",
  "Sludge": "污泥攻擊",
  "Mud Bomb": "泥漿爆彈",
  "Shadow Punch": "影子拳",
  "Psybeam": "幻象光線",
  "Water Pulse": "水之波動",
  "Horn Attack": "角擊",
  "Air Cutter": "空氣刀",
  "Magnet Bomb": "磁力炸彈",
  "Bulldoze": "踏平地面",
  "Rock Tomb": "岩石封印",
  "Scald": "熱湯",
  "Aerial Ace": "飛燕疾擊",
  "Bubble Beam": "泡沫光線",
  "Struggle": "掙扎",
  "Ancient Power": "原始之力",
  "Brine": "潮水",
  "Swift": "超速星",
  "Ominous Wind": "怪風",
  "Heart Stamp": "心靈烙印",
  "Dig": "挖洞",
  "Flame Wheel ": "烽火輪",
  "Vice Grip": "夾擊",
  "Parabolic Charge": "拋物線充電",
  "Flame Charge": "硝基衝擊",
  "Aqua Jet": "水壓噴射",
  "Poison Fang": "劇毒牙",
  "Twister": "神龍捲",
  "Draining Kiss": "吸取之吻",
  "Disarming Voice": "魅力之音",
  "Shadow Sneak": "暗影擊",
  "Mega Drain": "超級吸收",
  "Wrap(Pink/Green)": "捲起",
  "Icy Wind": "急凍風暴",
  "Wrap": "捲起"
}