module.exports = {
  "Psycho Cut": "超",
  "Mud Shot": "地",
  "Lick": "鬼",
  "Scratch": "普",
  "Water Gun": "水",
  "Metal Claw": "钢",
  "Shadow Claw": "鬼",
  "Wing Attack": "飞",
  "Vine Whip": "草",
  "Frost Breath": "冰",
  "Pound": "普",
  "Poison Jab": "毒",
  "Zen Headbutt": "超",
  "Bug Bite": "虫",
  "Bite": "恶",
  "Dragon Breath": "龙",
  "Feint Attack": "恶",
  "Steel Wing": "钢",
  "Fire Fang": "火",
  "Tackle": "普",
  "Cut": "普",
  "Poison Sting": "毒",
  "Razor Leaf": "草",
  "Spark": "电",
  "Sucker Punch": "恶",
  "Acid": "毒",
  "Ember": "火",
  "Rock Throw": "岩",
  "Peck": "飞",
  "Bullet Punch": "钢",
  "Low Kick": "斗",
  "Thunder Shock": "电",
  "Confusion": "超",
  "Quick Attack": "普",
  "Fury Cutter": "虫",
  "Karate Chop": "斗",
  "Ice Shard": "冰",
  "Bubble": "水",
  "Mud Slap": "地",
  "Rock Smash": "斗",
  "Splash": "水",
  "Cross Chop": "斗",
  "Body Slam": "普",
  "Dragon Claw": "龙",
  "Stone Edge": "岩",
  "Brick Break ": "斗",
  "Aqua Tail": "水",
  "Power Whip": "草",
  "Iron Head": "钢",
  "Gunk Shot": "毒",
  "Sludge Bomb": "毒",
  "Leaf Blade": "草",
  "Hurricane": "飞",
  "Thunderbolt": "电",
  "Psychic": "超",
  "Sludge Wave": "毒",
  "Flamethrower": "火",
  "Play Rough": "仙",
  "Megahorn": "虫",
  "Thunder Punch": "电",
  "Hyper Fang": "普",
  "Discharge": "电",
  "Cross Poison": "毒",
  "Heat Wave": "火",
  "Hydro Pump": "水",
  "Petal Blizzard": "草",
  "Blizzard": "冰",
  "Thunder": "电",
  "Psyshock": "超",
  "Moonblast": "仙",
  "Fire Blast": "火",
  "Earthquake": "地",
  "Submission": "斗",
  "X-Scissor": "虫",
  "Flash Cannon": "钢",
  "Drill Run": "地",
  "Hyper Beam": "普",
  "Dragon Pulse": "龙",
  "Power Gem": "岩",
  "Psystrike": "超",
  "Ice Beam": "冰",
  "Solar Beam": "草",
  "Shadow Ball": "鬼",
  "Dark Pulse": "恶",
  "Ice Punch": "冰",
  "Seed Bomb": "草",
  "Rock Slide": "岩",
  "Bone Club": "地",
  "Fire Punch": "火",
  "Flame Burst": "火",
  "Stomp": "普",
  "Bug Buzz": "虫",
  "Signal Beam": "虫",
  "Drill Peck": "飞",
  "Low Sweep": "斗",
  "Night Slash": "恶",
  "Rest": "超",
  "Dazzling Gleam": "仙",
  "Giga Drain": "草",
  "Sludge": "毒",
  "Mud Bomb": "地",
  "Shadow Punch": "鬼",
  "Psybeam": "超",
  "Water Pulse": "水",
  "Horn Attack": "普",
  "Air Cutter": "飞",
  "Magnet Bomb": "钢",
  "Bulldoze": "地",
  "Rock Tomb": "岩",
  "Scald": "水",
  "Aerial Ace": "飞",
  "Bubble Beam": "水",
  "Struggle": "普",
  "Ancient Power": "岩",
  "Brine": "水",
  "Swift": "普",
  "Ominous Wind": "鬼",
  "Heart Stamp": "超",
  "Dig": "地",
  "Flame Wheel ": "火",
  "Vice Grip": "普",
  "Parabolic Charge": "电",
  "Flame Charge": "火",
  "Aqua Jet": "水",
  "Poison Fang": "毒",
  "Twister": "龙",
  "Draining Kiss": "仙",
  "Disarming Voice": "仙",
  "Shadow Sneak": "鬼",
  "Mega Drain": "草",
  "Wrap(Pink/Green)": "普",
  "Icy Wind": "冰",
  "Wrap": "普"
}