{
  "Psycho Cut": "精神切割",
  "Mud Shot": "泥浆喷射",
  "Lick": "舌舔",
  "Scratch": "抓",
  "Water Gun": "水枪",
  "Metal Claw": "金属爪",
  "Shadow Claw": "阴影爪",
  "Wing Attack": "翅膀拍击",
  "Vine Whip": "藤鞭",
  "Frost Breath": "冰之吐息",
  "Pound": "拍打",
  "Poison Jab": "毒突",
  "Zen Headbutt": "思念头槌",
  "Bug Bite": "虫食",
  "Bite": "啃咬",
  "Dragon Breath": "龙之吐息",
  "Feint Attack": "暗算",
  "Steel Wing": "钢之翼",
  "Fire Fang": "火之牙",
  "Tackle": "撞击",
  "Cut": "居合斩",
  "Poison Sting": "毒针",
  "Razor Leaf": "飞叶斩",
  "Spark": "电火花",
  "Sucker Punch": "偷袭",
  "Acid": "溶解液",
  "Ember": "火苗",
  "Rock Throw": "落石",
  "Peck": "啄",
  "Bullet Punch": "子弹拳",
  "Low Kick": "过肩摔",
  "Thunder Shock": "电击",
  "Confusion": "念力",
  "Quick Attack": "电光石火",
  "Fury Cutter": "连续切",
  "Karate Chop": "空手刀",
  "Ice Shard": "冰之砾",
  "Bubble": "水泡",
  "Mud Slap": "扔泥",
  "Rock Smash": "碎岩",
  "Splash": "水溅跃",
  "Cross Chop": "十字切",
  "Body Slam": "压制",
  "Dragon Claw": "龙之爪",
  "Stone Edge": "石刃",
  "Brick Break ": "瓦割",
  "Aqua Tail": "水之尾",
  "Power Whip": "强力鞭挞",
  "Iron Head": "铁头槌",
  "Gunk Shot": "粉尘射击",
  "Sludge Bomb": "淤泥爆弹",
  "Leaf Blade": "刃叶斩",
  "Hurricane": "暴风",
  "Thunderbolt": "十万伏特",
  "Psychic": "精神干扰",
  "Sludge Wave": "淤泥波",
  "Flamethrower": "火焰放射",
  "Play Rough": "嬉闹",
  "Megahorn": "百万角击",
  "Thunder Punch": "雷电拳",
  "Hyper Fang": "必杀门牙 ",
  "Discharge": "放电",
  "Cross Poison": "毒十字",
  "Heat Wave": "热风",
  "Hydro Pump": "水压",
  "Petal Blizzard": "花吹雪",
  "Blizzard": "暴风雪 ",
  "Thunder": "雷电",
  "Psyshock": "精神冲击",
  "Moonblast": "月爆",
  "Fire Blast": "大字火",
  "Earthquake": "地震",
  "Submission": "地狱车",
  "X-Scissor": "十字剪",
  "Flash Cannon": "光栅加农",
  "Drill Run": "钻头直击",
  "Hyper Beam": "破坏光线",
  "Dragon Pulse": "龙之波动",
  "Power Gem": "力量宝石 ",
  "Psystrike": "精神破坏",
  "Ice Beam": "冷冻光线",
  "Solar Beam": "太阳光线",
  "Shadow Ball": "阴影球",
  "Dark Pulse": "恶之波动",
  "Ice Punch": "冷冻拳",
  "Seed Bomb": "种子爆弹",
  "Rock Slide": "岩崩",
  "Bone Club": "骨头棍",
  "Fire Punch": "火焰拳",
  "Flame Burst": "爆裂火焰",
  "Stomp": "践踏",
  "Bug Buzz": "虫鸣",
  "Signal Beam": "信号光线",
  "Drill Peck": "钻孔啄",
  "Low Sweep": "下旋",
  "Night Slash": "试刀",
  "Rest": "睡眠",
  "Dazzling Gleam": "魔法闪光",
  "Giga Drain": "亿万吸取",
  "Sludge": "淤泥攻击",
  "Mud Bomb": "泥爆弹",
  "Shadow Punch": "暗影拳",
  "Psybeam": "精神光线",
  "Water Pulse": "水之波动",
  "Horn Attack": "角突",
  "Air Cutter": "空气刃",
  "Magnet Bomb": "磁体炸弹",
  "Bulldoze": "压路",
  "Rock Tomb": "岩石封",
  "Scald": "沸水",
  "Aerial Ace": "燕返",
  "Bubble Beam": "泡沫光线",
  "Struggle": "拼命",
  "Ancient Power": "原始力量",
  "Brine": "潮水",
  "Swift": "迅星",
  "Ominous Wind": "妖风",
  "Heart Stamp": "心灵压迫",
  "Dig": "挖洞",
  "Flame Wheel ": "火焰车",
  "Vice Grip": "夹",
  "Parabolic Charge": "抛物式充电",
  "Flame Charge": "硝化冲锋",
  "Aqua Jet": "水流喷射",
  "Poison Fang": "剧毒之牙",
  "Twister": "龙卷风",
  "Draining Kiss": "吸收之吻",
  "Disarming Voice": "魅力声音",
  "Shadow Sneak": "影击",
  "Mega Drain": "百万吸取",
  "Wrap(Pink/Green)": "卷紧",
  "Icy Wind": "冰冻之风",
  "Wrap": "卷紧"
}