{
  "Psycho Cut": "Psycho Cut",
  "Mud Shot": "Mud Shot",
  "Lick": "Lick",
  "Scratch": "Scratch",
  "Water Gun": "Water Gun",
  "Metal Claw": "Metal Claw",
  "Shadow Claw": "Shadow Claw",
  "Wing Attack": "Wing Attack",
  "Vine Whip": "Vine Whip",
  "Frost Breath": "Frost Breath",
  "Pound": "Pound",
  "Poison Jab": "Poison Jab",
  "Zen Headbutt": "Zen Headbutt",
  "Bug Bite": "Bug Bite",
  "Bite": "Bite",
  "Dragon Breath": "Dragon Breath",
  "Feint Attack": "Feint Attack",
  "Steel Wing": "Steel Wing",
  "Fire Fang": "Fire Fang",
  "Tackle": "Tackle",
  "Cut": "Cut",
  "Poison Sting": "Poison Sting",
  "Razor Leaf": "Razor Leaf",
  "Spark": "Spark",
  "Sucker Punch": "Sucker Punch",
  "Acid": "Acid",
  "Ember": "Ember",
  "Rock Throw": "Rock Throw",
  "Peck": "Peck",
  "Bullet Punch": "Bullet Punch",
  "Low Kick": "Low Kick",
  "Thunder Shock": "Thunder Shock",
  "Confusion": "Confusion",
  "Quick Attack": "Quick Attack",
  "Fury Cutter": "Fury Cutter",
  "Karate Chop": "Karate Chop",
  "Ice Shard": "Ice Shard",
  "Bubble": "Bubble",
  "Mud Slap": "Mud Slap",
  "Rock Smash": "Rock Smash",
  "Splash": "Splash",
  "Cross Chop": "Cross Chop",
  "Body Slam": "Body Slam",
  "Dragon Claw": "Dragon Claw",
  "Stone Edge": "Stone Edge",
  "Brick Break ": "Brick Break ",
  "Aqua Tail": "Aqua Tail",
  "Power Whip": "Power Whip",
  "Iron Head": "Iron Head",
  "Gunk Shot": "Gunk Shot",
  "Sludge Bomb": "Sludge Bomb",
  "Leaf Blade": "Leaf Blade",
  "Hurricane": "Hurricane",
  "Thunderbolt": "Thunderbolt",
  "Psychic": "Psychic",
  "Sludge Wave": "Sludge Wave",
  "Flamethrower": "Flamethrower",
  "Play Rough": "Play Rough",
  "Megahorn": "Megahorn",
  "Thunder Punch": "Thunder Punch",
  "Hyper Fang": "Hyper Fang",
  "Discharge": "Discharge",
  "Cross Poison": "Cross Poison",
  "Heat Wave": "Heat Wave",
  "Hydro Pump": "Hydro Pump",
  "Petal Blizzard": "Petal Blizzard",
  "Blizzard": "Blizzard",
  "Thunder": "Thunder",
  "Psyshock": "Psyshock",
  "Moonblast": "Moonblast",
  "Fire Blast": "Fire Blast",
  "Earthquake": "Earthquake",
  "Submission": "Submission",
  "X-Scissor": "X-Scissor",
  "Flash Cannon": "Flash Cannon",
  "Drill Run": "Drill Run",
  "Hyper Beam": "Hyper Beam",
  "Dragon Pulse": "Dragon Pulse",
  "Power Gem": "Power Gem",
  "Psystrike": "Psystrike",
  "Ice Beam": "Ice Beam",
  "Solar Beam": "Solar Beam",
  "Shadow Ball": "Shadow Ball",
  "Dark Pulse": "Dark Pulse",
  "Ice Punch": "Ice Punch",
  "Seed Bomb": "Seed Bomb",
  "Rock Slide": "Rock Slide",
  "Bone Club": "Bone Club",
  "Fire Punch": "Fire Punch",
  "Flame Burst": "Flame Burst",
  "Stomp": "Stomp",
  "Bug Buzz": "Bug Buzz",
  "Signal Beam": "Signal Beam",
  "Drill Peck": "Drill Peck",
  "Low Sweep": "Low Sweep",
  "Night Slash": "Night Slash",
  "Rest": "Rest",
  "Dazzling Gleam": "Dazzling Gleam",
  "Giga Drain": "Giga Drain",
  "Sludge": "Sludge",
  "Mud Bomb": "Mud Bomb",
  "Shadow Punch": "Shadow Punch",
  "Psybeam": "Psybeam",
  "Water Pulse": "Water Pulse",
  "Horn Attack": "Horn Attack",
  "Air Cutter": "Air Cutter",
  "Magnet Bomb": "Magnet Bomb",
  "Bulldoze": "Bulldoze",
  "Rock Tomb": "Rock Tomb",
  "Scald": "Scald",
  "Aerial Ace": "Aerial Ace",
  "Bubble Beam": "Bubble Beam",
  "Struggle": "Struggle",
  "Ancient Power": "Ancient Power",
  "Brine": "Brine",
  "Swift": "Swift",
  "Ominous Wind": "Ominous Wind",
  "Heart Stamp": "Heart Stamp",
  "Dig": "Dig",
  "Flame Wheel ": "Flame Wheel ",
  "Vice Grip": "Vice Grip",
  "Parabolic Charge": "Parabolic Charge",
  "Flame Charge": "Flame Charge",
  "Aqua Jet": "Aqua Jet",
  "Poison Fang": "Poison Fang",
  "Twister": "Twister",
  "Draining Kiss": "Draining Kiss",
  "Disarming Voice": "Disarming Voice",
  "Shadow Sneak": "Shadow Sneak",
  "Mega Drain": "Mega Drain",
  "Wrap(Pink/Green)": "Wrap(Pink/Green)",
  "Icy Wind": "Icy Wind",
  "Wrap": "Wrap"
}